laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('page');;
//Admin
Route::resource('user','UserController');
Route::resource('coaching','CoachController');
Route::resource('investasi','InvestasiController');
Route::resource('umkm','UmkmController');
Route::resource('lelang','LelangController');

Auth::routes();
Route::group(['prefix' => 'admin'], function(){
    Route::get('/home', 'HomeController@index');
    Route::get('/users', 'UserController@index');
    Route::get('/lelang', 'LelangController@index');
    Route::get('/umkm', 'UmkmController@index');
    Route::get('/investasi', 'InvestasiController@index');
    Route::get('/coaching', 'CoachController@index')->name('coaching');
    Route::get('/coaching/assign/{id}', 'CoachController@assign')->name('coaching.assign');
    Route::put('/coaching/assigned/{id}', 'CoachController@assigned')->name('coaching.assigned');
});

Route::group(['prefix' => 'umkmuser'], function(){
    Route::get('/home', 'Umkmuser\UmkmController@index');
    Route::get('/profil', 'Umkmuser\UmkmController@profil');
    Route::get('/edit', 'Umkmuser\UmkmController@edit');
    Route::get('/chat', 'Umkmuser\UmkmController@chat');
    Route::get('/product', 'Umkmuser\UmkmController@product');
});
Route::resource('umkmuser','Umkmuser\UmkmController');


Route::group(['prefix' => 'investor'], function(){
    Route::get('/home', 'Investor\InvestorController@index');
    Route::get('/profil', 'Investor\InvestorController@profil');
    Route::get('/investasi', 'Investor\InvestorController@investasi');
    Route::get('/edit', 'Investor\InvestorController@edit');
    Route::get('/listumkm', 'Investor\InvestorController@listumkm');
    Route::get('/umkmdetail/{id}', 'Investor\InvestorController@umkmdetail')->name('investor.umkmdetail');
});
Route::resource('investor','Investor\InvestorController');


Route::group(['prefix' => 'coachuser'], function(){
    Route::get('/home', 'Coachuser\CoachController@index');
    Route::get('/profil', 'Coachuser\CoachController@profil');
    Route::get('/chat', 'Coachuser\CoachController@chat');
    Route::get('/edit', 'Coachuser\CoachController@edit');
});

Route::resource('coachuser','Coachuser\CoachController');

laravel/app/Coaching.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Coaching extends Model
{
    protected $fillable = [
        'ringkasan_masalah', 'coachingstatus_id', 'user_id', 'user_coach_id'
    ];

    public function coachingstatus()
    {
        return $this->belongsTo(Coachingstatus::class);
    }

    public function user() {
        return $this->belongsTo(User::class,'user_id');
    }

    public function userCoach() {
        return $this->belongsTo(User::class, 'user_coach_id');
    }

    public function coachingmessages()
    {
        return $this->hasMany(Coachingmessage::class);
    }

    public function coachingreports()
    {
        return $this->hasMany(Coachingreport::class);
    }
}

laravel/resources/views/admin/coaching/assign.blade.php
@extends('admin.admin')
@section('content')
    <!-- Main Section -->
    <div class="content-wrapper">
        <section class="content">
            <div class="content">
                <!-- Remove This Before You Start -->
                <h1>Edit Coaching</h1>
                <hr>


                    <form action="{{ route('coaching.assigned', $coacher[0]->id) }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <select name="coach" id="coach" class="select2-dropdown">
                            @foreach($data as $datas)
                            <option value="{{$datas->id}}">{{$datas->name}}</option>

                            @endforeach
                        </select>
                        <div><br /></div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-md btn-primary">Assign</button>
                            <button type="reset" class="btn btn-md btn-danger">Cancel</button>
                        </div>
                    </form>
            </div>
            <!-- /.content -->
        </section>
        <!-- /.main-section -->
    </div>
@endsection

laravel/resources/views/admin/coaching/coachs.blade.php
@extends('admin.admin')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">Coaching Management</h3>
                            <a href="" class=" btn btn-sm btn-primary">New Coaching</a>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Ringkasan Masalah</th>
                                    <th>Status</th>
                                    <th>Tipe</th>
                                    <th>User</th>
                                    <th>Coach</th>
                                    <th>Action</th>
                                    <th>Assign</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($coaching as $i => $coach)
                                    <tr>
                                        <td>{{ $i+1 }}</td>
                                        <td>{{ $coach->ringkasan_masalah }}</td>
                                        <td>{{ $coach->coachingstatus->name }}</td>
                                        @foreach ($coach->coachingreports as $report)
                                            <td>{{ $report->coachingreporttype->name }}</td>
                                        @endforeach
                                        <td>{{ $coach->user->name }}</td>
                                        @if(is_null($coach->user_coach_id))
                                            <td>Belum di assign</td>
                                        @else()
                                            <td>{{ $coach->userCoach->name }}</td>
                                        @endif
                                        <td>
                                            <form action="{{ route('coaching.destroy',$coach->id) }}" method="post">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                                <a href="{{ route('coaching.edit',$coach->id) }}" class=" btn btn-sm btn-primary">Edit</a>
                                                <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">Delete</button>
                                            </form>
                                        </td>
                                        <td><a href="{{ route('coaching.assign',$coach->id) }}" class=" btn btn-sm btn-success">Assign Coach</a></td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

laravel/resources/views/admin/coaching/edit.blade.php
@extends('admin.admin')
@section('content')
    <!-- Main Section -->
    <div class="content-wrapper">

        <section class="content">
            <div class="content">
                <!-- Remove This Before You Start -->
                <h1>Edit Coaching</h1>
                <hr>
                @foreach($data as $datas)
                    <form action="{{ route('coaching.update', $datas->id) }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <div class="form-group">
                            <label for="masalah">Ringkasan Masalah:</label>
                            <input type="text" class="form-control" id="masalah" name="masalah" value="{{ $datas->ringkasan_masalah }}">
                        </div>
                        <div class="form-group">
                            <label for="status">Status:</label>
                            <select name="status">
                                @foreach($datas->coachingstatus->get() as $status)
                                    <option class="form-control" id="status" value="{{ $status->id }}" {{ $datas->coachingstatus_id == $status->id ? 'selected="selected"' : '' }}>{{ $status->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="user">User:</label>
                            <select name="user">
                                @foreach($datas->user->where('usertype_id','=','2')->get() as $role)
                                    <option class="form-control" id="user" value="{{ $role->id }}" {{ $datas->user_id == $role->id ? 'selected="selected"' : '' }}>{{ $role->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-md btn-primary">Submit</button>
                            <button type="reset" class="btn btn-md btn-danger" onclick="history.back();">Cancel</button>
                        </div>
                    </form>
                @endforeach
            </div>
            <!-- /.content -->
        </section>
        <!-- /.main-section -->
    </div>
@endsection