laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('page');;
//Admin
Route::resource('user','UserController');
Route::resource('coaching','CoachController');
Route::resource('investasi','InvestasiController');
Route::resource('umkm','UmkmController');
Route::resource('lelang','LelangController');

Auth::routes();
Route::group(['prefix' => 'admin'], function(){
    Route::get('/home', 'HomeController@index');
    Route::get('/users', 'UserController@index');
    Route::get('/lelang', 'LelangController@index');
    Route::get('/umkm', 'UmkmController@index');
    Route::get('/investasi', 'InvestasiController@index');
    Route::get('/coaching', 'CoachController@index')->name('coaching');
    Route::get('/coaching/assign/{id}', 'CoachController@assign')->name('coaching.assign');
    Route::put('/coaching/assigned/{id}', 'CoachController@assigned')->name('coaching.assigned');
});

Route::group(['prefix' => 'umkmuser'], function(){
    Route::get('/home', 'Umkmuser\UmkmController@index');
    Route::get('/profil', 'Umkmuser\UmkmController@profil');
    Route::get('/edit', 'Umkmuser\UmkmController@edit');
    Route::get('/chat', 'Umkmuser\UmkmController@chat');
    Route::get('/product', 'Umkmuser\UmkmController@product');
});
Route::resource('umkmuser','Umkmuser\UmkmController');


Route::group(['prefix' => 'investor'], function(){
    Route::get('/home', 'Investor\InvestorController@index');
    Route::get('/profil', 'Investor\InvestorController@profil');
    Route::get('/investasi', 'Investor\InvestorController@investasi');
    Route::get('/edit', 'Investor\InvestorController@edit');
    Route::get('/listumkm', 'Investor\InvestorController@listumkm');
    Route::get('/umkmdetail/{id}', 'Investor\InvestorController@umkmdetail')->name('investor.umkmdetail');
});
Route::resource('investor','Investor\InvestorController');


Route::group(['prefix' => 'coachuser'], function(){
    Route::get('/home', 'Coachuser\CoachController@index');
    Route::get('/profil', 'Coachuser\CoachController@profil');
    Route::get('/chat', 'Coachuser\CoachController@chat');
    Route::get('/edit', 'Coachuser\CoachController@edit');
});

Route::resource('coachuser','Coachuser\CoachController');

laravel/app/Http/Controllers/UmkmController.php
<?php

namespace App\Http\Controllers;

use App\Ukm;
use App\Ukmcategory;
use Illuminate\Http\Request;

class UmkmController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index(Request $request)
    {
        $request->user()->authorizeRoles(['1']);

        $umkmkat = Ukmcategory::all();
        return view('admin.umkm.umkm', compact('umkmkat'));
    }
    public function create(Request $request)
    {
        return view('admin.umkm.register');
    }
    public function store(Request $request)
    {
        $data = new Ukmcategory();
        $data->name = $request->name;
        $data->description = $request->description;
        $data->save();
        return redirect()->route('umkm.index')->with('alert-success','Berhasil Menambahkan Data!');
    }
    public function edit($id)
    {
        $data = Ukmcategory::where('id',$id)->get();

        return view('admin.umkm.edit',compact('data'));
    }
    public function update(Request $request, $id)
    {
        $data = Ukmcategory::where('id',$id)->first();
        $data->name = $request->name;
        $data->description = $request->description;
        $data->save();
        return redirect()->route('umkm.index')->with('alert-success','Data berhasil diubah!');
    }
    public function destroy($id)
    {
        $data = Ukmcategory::where('id',$id)->first();
        $data->delete();
        return redirect()->route('umkm.index')->with('alert-success','Data berhasi dihapus!');
    }
}

laravel/app/Http/Controllers/Umkmuser/UmkmController.php
<?php

namespace App\Http\Controllers\Umkmuser;

use App\Http\Controllers\Controller;
use App\Ukm;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\User;

class UmkmController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        //$request->user()->authorizeRoles(['1']);
        //cho Auth::user()->usertype->name;

        //echo User::all();
        //$userid = Auth::user()->id;
        //$users = Auth::user();
        return view('umkm.home');
    }
    public function profil()
    {
        $data = Auth::user();

        return view('umkm.profil',compact('data'));
    }
    public function edit()
    {
        $id = Auth::user()->id;
        $datas = User::where('id',$id)->first();

        return view('umkm.edit',compact('datas'));
    }
    public function chat()
    {
        return view('umkm.chat');
    }
    public function product()
    {
        return view('umkm.product');
    }
    public function update(Request $request)
    {
        $id = Auth::user()->id;
        $data = User::where('id',$id)->first();
        $data->ukm->name = $request->name;
        $data->ukm->jenis_usaha = $request->jenis_usaha;
        $data->ukm->tahun_berdiri = $request->tahun_berdiri;
        $data->phone = $request->phone;
        $data->ukm->jumlah_tenaga_kerja = $request->jumlah_tenaga_kerja;
        $data->ukm->legalitas_usaha = $request->legalitas_usaha;
        $data->ukm->penjualan_per_bulan = $request->penjualan_per_bulan;
        $data->email = $request->email;
        $data->address = $request->address;
        $data->ukm->save();
        $data->save();
        return redirect()->route('umkmuser.index')->with('alert-success','Data berhasil diubah!');
    }
    public function destroy($id)
    {
        $data = User::where('id',$id)->first();
        $data->delete();
        return redirect()->route('umkm.index')->with('alert-success','Data berhasi dihapus!');
    }
}

laravel/resources/views/admin/umkm/edit.blade.php
@extends('admin.admin')
@section('content')
    <!-- Main Section -->
    <div class="content-wrapper">

        <section class="content">
            <div class="content">
                <!-- Remove This Before You Start -->
                <h1>Edit UMKM kategory</h1>
                <hr>
                @foreach($data as $datas)
                    <form action="{{ route('umkm.update', $datas->id) }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <div class="form-group">
                            <label for="name">Name:</label>
                            <input type="text" class="form-control" id="name" name="name" value="{{ $datas->name }}">
                        </div>
                        <div class="form-group">
                            <label for="description">Deskripsi:</label>
                            <input type="text" class="form-control" id="description" name="description" value="{{ $datas->description }}">
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-md btn-primary">Submit</button>
                            <button type="reset" class="btn btn-md btn-danger" onclick="history.back();">Cancel</button>
                        </div>
                    </form>
                @endforeach
            </div>
            <!-- /.content -->
        </section>
        <!-- /.main-section -->
    </div>
@endsection

laravel/resources/views/admin/umkm/register.blade.php
@extends('admin.admin')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        <!-- Main content -->
        <section class="content">
            <div class="content">
                <!-- Remove This Before You Start -->
                <h1>Tambah Kategori UMKM</h1>
                <hr>
                <form action="{{ route('umkm.store') }}" method="post">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="name">Name:</label>
                        <input type="text" class="form-control" id="name" name="name">
                    </div>
                    <div class="form-group">
                        <label for="description">Description:</label>
                        <input type="text" class="form-control" id="description" name="description">
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-md btn-primary">Submit</button>
                        <button type="reset" class="btn btn-md btn-danger">Cancel</button>
                    </div>
                </form>
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

laravel/resources/views/admin/umkm/umkm.blade.php
@extends('admin.admin')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">UMKM Management</h3>
                            <a href="{{ route('umkm.create') }}" class=" btn btn-sm btn-primary">Create</a>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Nama</th>
                                    <th>Desc</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($umkmkat as $i => $umkmk)
                                    <tr>
                                        <td>{{ $i+1 }}</td>
                                        <td>{{ $umkmk->name }}</td>
                                        <td>{{ $umkmk->description }}</td>
                                        <td>
                                            <form action="{{ route('umkm.destroy', $umkmk->id) }}" method="post">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                                <a href="{{ route('umkm.edit',$umkmk->id) }}" class=" btn btn-sm btn-primary">Edit</a>
                                                <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection