laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('page');;
//Admin
Route::resource('user','UserController');
Route::resource('coaching','CoachController');
Route::resource('investasi','InvestasiController');
Route::resource('umkm','UmkmController');
Route::resource('lelang','LelangController');

Auth::routes();
Route::group(['prefix' => 'admin'], function(){
    Route::get('/home', 'HomeController@index');
    Route::get('/users', 'UserController@index');
    Route::get('/lelang', 'LelangController@index');
    Route::get('/umkm', 'UmkmController@index');
    Route::get('/investasi', 'InvestasiController@index');
    Route::get('/coaching', 'CoachController@index')->name('coaching');
    Route::get('/coaching/assign/{id}', 'CoachController@assign')->name('coaching.assign');
    Route::put('/coaching/assigned/{id}', 'CoachController@assigned')->name('coaching.assigned');
});

Route::group(['prefix' => 'umkmuser'], function(){
    Route::get('/home', 'Umkmuser\UmkmController@index');
    Route::get('/profil', 'Umkmuser\UmkmController@profil');
    Route::get('/edit', 'Umkmuser\UmkmController@edit');
    Route::get('/chat', 'Umkmuser\UmkmController@chat');
    Route::get('/product', 'Umkmuser\UmkmController@product');
});
Route::resource('umkmuser','Umkmuser\UmkmController');


Route::group(['prefix' => 'investor'], function(){
    Route::get('/home', 'Investor\InvestorController@index');
    Route::get('/profil', 'Investor\InvestorController@profil');
    Route::get('/investasi', 'Investor\InvestorController@investasi');
    Route::get('/edit', 'Investor\InvestorController@edit');
    Route::get('/listumkm', 'Investor\InvestorController@listumkm');
    Route::get('/umkmdetail/{id}', 'Investor\InvestorController@umkmdetail')->name('investor.umkmdetail');
});
Route::resource('investor','Investor\InvestorController');


Route::group(['prefix' => 'coachuser'], function(){
    Route::get('/home', 'Coachuser\CoachController@index');
    Route::get('/profil', 'Coachuser\CoachController@profil');
    Route::get('/chat', 'Coachuser\CoachController@chat');
    Route::get('/edit', 'Coachuser\CoachController@edit');
});

Route::resource('coachuser','Coachuser\CoachController');

laravel/resources/views/admin/admin.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
    @include('head')
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">
    @include('header')
    <!-- Left side column. contains the logo and sidebar -->
    @include('admin.sidebar-left')

    @yield('content')

    @include('footer')

    <!-- Control Sidebar -->
    @include('admin.sidebar-right')
    <!-- /.control-sidebar -->
    <!-- Add the sidebar's background. This div must be placed
         immediately after the control sidebar -->
    <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->
@include('setting')
</body>
</html>

laravel/resources/views/admin/edit.blade.php
@extends('admin.admin')
@section('content')
    <!-- Main Section -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Data Tables
                <small>advanced tables</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Tables</a></li>
                <li class="active">Data tables</li>
            </ol>
        </section>

        <section class="content">
            <div class="content">
                <!-- Remove This Before You Start -->
                <h1>Anak IT -  Edit Kontak</h1>
                <hr>
                @foreach($data as $datas)
                    <form action="{{ route('user.update', $datas->id) }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('PUT') }}
                        <div class="form-group">
                            <label for="name">Nama:</label>
                            <input type="text" class="form-control" id="usr" name="name" value="{{ $datas->name }}">
                        </div>
                        <div class="form-group">
                            <label for="email">Email:</label>
                            <input type="email" class="form-control" id="email" name="email" value="{{ $datas->email }}">
                        </div>
                        <div class="form-group">
                            <label for="password">Password:</label>
                            <input type="text" class="form-control" id="password" name="password" onfocus="this.value=''" value="********">
                        </div>
                        <div class="form-group">
                            <label for="phone">Telepon:</label>
                            <input type="text" class="form-control" id="phone" name="phone" value="{{ $datas->phone }}">
                        </div>
                        <div class="form-group">
                            <label for="address">Alamat:</label>
                            <input type="textarea" class="form-control" id="address" name="address" value="{{ $datas->address }}">
                        </div>
                        <div class="form-group">
                            <label for="about">Keterangan:</label>
                            <input type="text" class="form-control" id="about" name="about" value="{{ $datas->about }}">
                        </div>
                        <div class="form-group">
                            <label for="is_added_to_elearning">Apakah sudah masuk E-learning:</label><br />
                            <input type="radio" id="is_added_to_elearning" name="is_added_to_elearning" {{ ($datas->is_added_to_elearning==1) ? "checked" : "true" }} value="1">Sudah
                            <input type="radio" id="is_added_to_elearning" name="is_added_to_elearning" {{ ($datas->is_added_to_elearning==0) ? "checked" : "true" }} value="0">Belum
                        </div>
                        <div class="form-group">
                            <label for="is_added_to_forum">Apakah sudah masuk Forum:</label><br />
                            <input type="radio" id="is_added_to_forum" name="is_added_to_forum" {{ ($datas->is_added_to_forum==1) ? "checked" : "true" }} value="1">Sudah
                            <input type="radio" id="is_added_to_forum" name="is_added_to_forum" {{ ($datas->is_added_to_forum==0) ? "checked" : "true" }} value="0">Belum
                        </div>
                        <div class="form-group">
                            <button type="submit" class="btn btn-md btn-primary">Submit</button>
                            <button type="reset" class="btn btn-md btn-danger" onclick="history.back();">Cancel</button>
                        </div>
                    </form>
                @endforeach
            </div>
            <!-- /.content -->
        </section>
        <!-- /.main-section -->
    </div>
@endsection

laravel/resources/views/admin/home.blade.php
@extends('admin.admin')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        Selamat Datang di Halaman Admin
    </div>
    <!-- /.content-wrapper -->
@endsection

laravel/resources/views/admin/register.blade.php
@extends('admin.admin')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Data Tables
                <small>advanced tables</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Tables</a></li>
                <li class="active">Data tables</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="content">
                <!-- Remove This Before You Start -->
                <h1>Tambah User</h1>
                <hr>
                <form action="{{ route('user.store') }}" method="post">
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="nama">Nama:</label>
                        <input type="text" class="form-control" id="user" name="name">
                    </div>
                    <div class="form-group">
                        <label for="email">Email:</label>
                        <input type="email" class="form-control" id="email" name="email">
                    </div>
                    <div class="form-group">
                        <label for="password">Password:</label>
                        <input type="text" class="form-control" id="password" name="password">
                    </div>
                    <div class="form-group">
                        <label for="phone">Telepon:</label>
                        <input type="text" class="form-control" id="phone" name="phone">
                    </div>
                    <div class="form-group">
                        <label for="address">Alamat:</label>
                        <input type="textarea" class="form-control" id="address" name="address">
                    </div>
                    <div class="form-group">
                        <label for="about">Keterangan :</label>
                        <input type="text" class="form-control" id="about" name="about">
                    </div>
                    <div class="form-group">
                        <label for="usertype">Usertype:</label>
                        <select class="form-control" id="usertype" name="usertype">
                            <option value="1">Administrator</option>
                            <option value="2">Umkm</option>
                            <option value="3">Coach</option>
                            <option value="4">Investor</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="is_added_to_elearning">Apakah sudah masuk E-learning:</label><br />
                        <input type="radio" id="is_added_to_elearning" name="is_added_to_elearning" value="1">Sudah
                        <input type="radio" id="is_added_to_elearning" name="is_added_to_elearning" value="0">Belum
                    </div>
                    <div class="form-group">
                        <label for="is_added_to_forum">Apakah sudah masuk Forum:</label><br />
                        <input type="radio" id="is_added_to_forum" name="is_added_to_forum" value="1">Sudah
                        <input type="radio" id="is_added_to_forum" name="is_added_to_forum" value="0">Belum
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-md btn-primary">Submit</button>
                        <button type="reset" class="btn btn-md btn-danger">Cancel</button>
                    </div>
                </form>
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

laravel/resources/views/admin/sidebar-left.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>
            <li>
                <a href="{{url('admin/coaching')}}">
                    <i class="fa fa-table"></i> <span>Coaching Management</span>
                </a>
            </li>
            <li>
                <a href="{{url('admin/investasi')}}">
                    <i class="fa fa-table"></i> <span>Investasi Management</span>
                </a>
            </li>
            <li>
                <a href="{{url('admin/lelang')}}">
                    <i class="fa fa-table"></i> <span>Lelang Management</span>
                </a>
            </li>
            <li>
                    <a href="{{url('admin/umkm')}}">
                    <i class="fa fa-table"></i> <span>UMKM Management</span>
                </a>
            </li>
            <li>
                <a href="{{url('admin/users')}}">
                    <i class="fa fa-table"></i> <span>User Management</span>
                </a>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

laravel/resources/views/admin/sidebar-right.blade.php
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-user bg-yellow"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                            <p>New phone +1(800)555-1234</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                            <p>nora@example.com</p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <i class="menu-icon fa fa-file-code-o bg-green"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                            <p>Execution time 5 seconds</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">70%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Update Resume
                            <span class="label label-success pull-right">95%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-success" style="width: 95%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Laravel Integration
                            <span class="label label-warning pull-right">50%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="javascript:void(0)">
                        <h4 class="control-sidebar-subheading">
                            Back End Framework
                            <span class="label label-primary pull-right">68%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

        </div>
        <!-- /.tab-pane -->
        <!-- Stats tab content -->
        <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
        <!-- /.tab-pane -->
        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Allow mail redirect
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Other sets of options are available
                    </p>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Expose author name in posts
                        <input type="checkbox" class="pull-right" checked>
                    </label>

                    <p>
                        Allow the user to show his name in blog posts
                    </p>
                </div>
                <!-- /.form-group -->

                <h3 class="control-sidebar-heading">Chat Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Show me as online
                        <input type="checkbox" class="pull-right" checked>
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Turn off notifications
                        <input type="checkbox" class="pull-right">
                    </label>
                </div>
                <!-- /.form-group -->

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Delete chat history
                        <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                    </label>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside>

laravel/resources/views/admin/users.blade.php
@extends('admin.admin')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box">
                        <div class="box-header">
                            <h3 class="box-title">User Management</h3>
                            <a href="{{ route('user.create') }}" class=" btn btn-sm btn-primary">Create</a>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <table id="example1" class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Nama</th>
                                    <th>Role</th>
                                    <th>Email</th>
                                    <th>Phone</th>
                                    <th>E-Learning</th>
                                    <th>Forum</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($users as $i => $user)
                                    <tr>
                                        <td>{{ $i+1 }}</td>
                                        <td>{{ $user->name }}</td>
                                        <td>{{ $user->usertype->name }}</td>
                                        <td>{{ $user->email }}</td>
                                        <td>{{ $user->phone }}</td>
                                        @if(is_null($user->is_added_to_elearning) or $user->is_added_to_elearning<1)
                                            <td>Belum terdaftar</td>
                                        @else()
                                            <td>Terdaftar</td>
                                        @endif
                                        @if(is_null($user->is_added_to_forum) or $user->is_added_to_forum<1)
                                            <td>Belum terdaftar</td>
                                        @else()
                                            <td>Terdaftar</td>
                                        @endif
                                        <td>
                                            <form action="{{ route('user.destroy', $user->id) }}" method="post">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                                <a href="{{ route('user.edit',$user->id) }}" class=" btn btn-sm btn-primary">Edit</a>
                                                <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection